import type { Metadata } from "next";
import { Roboto, Merriweather } from 'next/font/google';
import {PostProvider} from "@/Context/PostProvider"
import "./globals.css";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export const merriweather = Merriweather({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-merriweather'
})

export const metadata: Metadata = {
  title: "Ai Traveling",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} antialiased`}
    >
      <body>
        <PostProvider>
          {children}
        </PostProvider>
      </body>
    </html>
  );
}
